//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakkaan_henkilötiedot
    {
        public string Asiakkaan_nimi { get; set; }
        public string Asiakkaan_lähiomaiset { get; set; }
        public string Laskutustiedot { get; set; }
        public string Yleinen_edunvalvoja { get; set; }
        public string Muuttotiedot { get; set; }
        public string Muut_tiedot { get; set; }
        public string Perustiedot { get; set; }
    }
}
