//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakkaan_omaisuu
    {
        public string Asiakkaan_nimi { get; set; }
        public string Henkilökohtaiset_tavarat { get; set; }
        public string Huonekalut { get; set; }
        public string Tekstiilit { get; set; }
        public string Vuode_ja_liinavaatteet { get; set; }
    }
}
