//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakkaan_hoitotiedot
    {
        public string Asiakkaan_nimi { get; set; }
        public string Asukkaan_perustiedot { get; set; }
        public string Edunvalvojan_yhteystiedot { get; set; }
        public string Omahoitajan_yhteystiedot { get; set; }
        public string Hoitavan_lääkärin_yhteystiedot { get; set; }
        public string Omaisten_yhteystiedot { get; set; }
        public string Diagnoosit { get; set; }
        public string Allergiat { get; set; }
        public string Kontrolloitavat_laboratoriokokeet { get; set; }
        public Nullable<System.DateTime> Sovitut_ja_suunnitellut_kontrollikäynnit { get; set; }
        public string Syöminen_erityisruokavalio { get; set; }
        public string Liikkuminen__hygienia { get; set; }
        public string Ihon_kunto { get; set; }
        public string Erityishoidot { get; set; }
        public string Kommunikointi { get; set; }
        public string Psyykkinen_vointi { get; set; }
        public string Hoitoon_hakeutumisen_syy { get; set; }
    }
}
