//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakkaan_rahan_käyttö
    {
        public string Asiakkaan_nimi { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<decimal> Nostot { get; set; }
        public Nullable<System.DateTime> Päiväys { get; set; }
        public Nullable<decimal> Määrä { get; set; }
        public string Käyttötarkoitus { get; set; }
        public string Kuittaaja { get; set; }
    }
}
