//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fysioterapian_kirjaukset
    {
        public string Asiakkaan_nimi { get; set; }
        public string Apuvälineiden_käyttö_ja_ohjaus { get; set; }
        public string Ohjeet_toiminnan_ylläpitämiseksi { get; set; }
    }
}
