//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infektion_seuranta_ja_hoito
    {
        public string Asiakkaan_nimi { get; set; }
        public Nullable<System.DateTime> Milloin_infektio_todettu { get; set; }
        public string Infektion_tyyppi { get; set; }
        public string Oireet { get; set; }
        public string Hoito { get; set; }
        public string Mahdolliset_kontrollit { get; set; }
    }
}
