//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lääkärin_lausunnot_ja_hoitosuunnitelmat
    {
        public string Asiakkaan_nimi { get; set; }
        public string Psykiatrian_lausunnot_ja_hoitosuunnitelmat { get; set; }
        public string Neurologian_lausunnot_ja_hoitosuunnitelmat { get; set; }
        public string Yleislääketied_lausunnot_ja_hoitosuunnitelmat { get; set; }
    }
}
