//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lääkelista
    {
        public string Asiakkaan_nimi { get; set; }
        public string Nykyhetken_lääkitys { get; set; }
        public string Lääkitys_historia { get; set; }
    }
}
