//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tehtävälista_asukkaan_saapuessa_palvelutaloon
    {
        public string Asiakkaan_nimi { get; set; }
        public string Omahoitajan_nimeäminen { get; set; }
        public string Tilojen_ja_päivärytminen_esittely { get; set; }
        public string Asukasopas { get; set; }
        public string Rekisteriselosteesta_kertominen { get; set; }
        public string Asiakkaan_oikeuksien_ja_velvollisuuksien_läpi_käyminen { get; set; }
        public string Vuokrasopimuksen_tekeminen { get; set; }
        public string Asumistuen_hakeminen { get; set; }
        public string Eläkkeensaajan_hoitotuen_hakeminen { get; set; }
        public string Muuttoilmoitus { get; set; }
        public string Valtakirja_apteekkia_varten { get; set; }
        public string E_resepti_suostumus { get; set; }
        public string Asiakasmaksuista_tiedottaminen { get; set; }
        public string Asukaskansion_laatiminen { get; set; }
        public string Henkilötietojen_kirjaaminen { get; set; }
        public string Raha_asioiden_hoito_ja_edunvalvojan_nimeäminen { get; set; }
        public string Omaisuusluettelon_laatiminen { get; set; }
    }
}
