//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTiKa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vointi_päiväkirja
    {
        public string Asiakkaan_nimi { get; set; }
        public string Hoidon_tarpeen_kirjaaminen { get; set; }
        public string Hoidon_tavoitteiden_kirjaaminen { get; set; }
        public string Hoidon_suunnittelun_kirjaaminen { get; set; }
        public string Hoidon_toteutuksen_kirjaaminen { get; set; }
    }
}
